# -*- coding: utf-8 -*-
# Cuerpo del informe: Auditoria Financiera CREARD (ReportLab)
# Ruta Report: SimpleDocTemplate (sin TOC), portada aparte via html2poster
import os
import sys

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, Image, KeepTogether, CondPageBreak,
                                HRFlowable)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#504933')
COVER_BLOCK   = colors.HexColor('#867b5a')
BORDER        = colors.HexColor('#cfcab8')
ICON          = colors.HexColor('#8c7e52')
ACCENT        = colors.HexColor('#87702a')
ACCENT_2      = colors.HexColor('#3a95b4')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')
SEM_SUCCESS   = colors.HexColor('#46875c')
SEM_WARNING   = colors.HexColor('#a18347')
SEM_ERROR     = colors.HexColor('#92453e')

MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN

# ─── Estilos ───
h1 = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4)
h2 = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                      textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=10)
bullet = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=17,
                        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                        leftIndent=16, spaceAfter=8)
caption = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                         textColor=TEXT_MUTED, alignment=TA_CENTER,
                         spaceBefore=3, spaceAfter=6)
th = ParagraphStyle('TH', fontName='FreeSerif', fontSize=10, leading=13,
                    textColor=colors.white, alignment=TA_CENTER)
td_l = ParagraphStyle('TDL', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_LEFT)
td_r = ParagraphStyle('TDR', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_RIGHT)
td_c = ParagraphStyle('TDC', fontName='FreeSerif', fontSize=9.5, leading=13,
                      textColor=TEXT_PRIMARY, alignment=TA_CENTER)
stat_big = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=17, leading=21,
                          textColor=ACCENT, alignment=TA_CENTER)
stat_lbl = ParagraphStyle('StatLbl', fontName='FreeSerif', fontSize=8, leading=11,
                          textColor=TEXT_MUTED, alignment=TA_CENTER)


def money(x):
    s = f'{x:,.2f}'.replace(',', '@').replace('.', ',').replace('@', '.')
    return f'S/ {s}'


def heading(num, text):
    """H1 con regla de acento (KeepTogether con la regla)."""
    p = Paragraph(f'<b>{num}. {text}</b>', h1)
    rule = HRFlowable(width='100%', thickness=1.2, color=ACCENT,
                      spaceBefore=0, spaceAfter=12)
    return [CondPageBreak(AVAIL_H * 0.25), KeepTogether([p, rule])]


def callout_row(items):
    """Fila de 3 tarjetas metricas (CalloutBox)."""
    cells = []
    for val, lbl in items:
        inner = Table([[Paragraph(f'<b>{val}</b>', stat_big)],
                       [Paragraph(lbl, stat_lbl)]],
                      colWidths=[AVAIL_W / 3 - 12])
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 1, ACCENT),
            ('TOPPADDING', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, -1), (-1, -1), 9),
            ('TOPPADDING', (0, 1), (-1, 1), 1),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 1),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        cells.append(inner)
    row = Table([cells], colWidths=[AVAIL_W / 3] * 3, hAlign='CENTER')
    row.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    return row


def std_table(header, rows, ratios, styles_per_col, highlight_rows=None):
    """Tabla estandar: header HEADER_FILL + blancas negrita, rayado TABLE_STRIPE."""
    col_w = [r * AVAIL_W for r in ratios]
    assert sum(col_w) <= AVAIL_W + 0.5, 'tabla excede ancho disponible'
    data = [[Paragraph(f'<b>{c}</b>', th) for c in header]]
    for r_i, row in enumerate(rows):
        line = []
        for c_i, cell in enumerate(row):
            line.append(Paragraph(str(cell), styles_per_col[c_i]))
        data.append(line)
    t = Table(data, colWidths=col_w, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      colors.white if i % 2 == 1 else TABLE_STRIPE))
    for hr in (highlight_rows or []):
        style.append(('BACKGROUND', (0, hr), (-1, hr), CARD_BG))
    t.setStyle(TableStyle(style))
    return t


def fit_image(img_path, max_w, max_h):
    pil = PILImage.open(img_path)
    ow, oh = pil.size
    ratio = min(max_w / ow if ow > max_w else 1.0,
                max_h / oh if oh > max_h else 1.0)
    return Image(img_path, width=ow * ratio, height=oh * ratio)


def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch,
                      'Auditoría Financiera CREARD')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.drawString(MARGIN, 0.45 * inch, 'CREARD · Sistema de Reservas Deportivas')
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(doc.page))
    canvas.restoreState()


doc = SimpleDocTemplate(
    '/home/z/my-project/scripts/audit_body.pdf', pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN,
    title='Auditoría Financiera CREARD', author='Z.ai', creator='Z.ai',
    subject='Auditoría de ingresos, métodos de pago y caja del sistema CREARD')

story = []

# ════ 1. RESUMEN EJECUTIVO ════
story += heading(1, 'Resumen Ejecutivo')
story.append(Paragraph(
    'El presente informe audita la situación financiera del sistema CREARD a partir de los datos '
    'reales de producción (proyecto Firebase <b>creard-8debc</b>), extraídos en vivo el '
    '<b>10 de septiembre de 2026</b> mediante sesión de super administrador sobre la API desplegada en '
    'Vercel. La muestra auditada comprende <b>149 reservas</b> (65 completadas, 63 reservadas y 21 '
    'canceladas), <b>46 registros de pago</b>, <b>6 registros de adelantos por cancelaciones</b> y '
    '<b>1 egreso</b>. Se verificaron partidas por partida los Ingresos Totales, el desglose por método '
    'de pago (Yape, Plin, efectivo y otros), los Adelantos por Cancelaciones con sus montos retenidos '
    'y devueltos, y el balance de caja que muestra el panel de Finanzas.', body))
story.append(Spacer(1, 6))
story.append(callout_row([
    (money(5203.50), 'INGRESOS TOTALES<br/>(criterio del panel)'),
    (money(882.50), 'YAPE + PLIN<br/>17,0% de los ingresos'),
    (money(4824.00), 'BALANCE EN CAJA<br/>(tras egresos y devoluciones)'),
]))
story.append(Spacer(1, 12))
story.append(Paragraph(
    'La aritmética interna del panel de Finanzas es <b>coherente y reproducible</b>: cada cifra '
    'públicamente visible se reconstruyó desde los datos crudos y cuadró sin diferencias. Sin embargo, '
    'la auditoría identificó <b>un defecto crítico de software y seis hallazgos de datos</b> que '
    'distorsionan o dificultan la gestión financiera. El defecto crítico —el endpoint '
    '<b>/api/retained-advances</b> respondía siempre 403 por un error de lectura del rol en el control '
    'de acceso— impedía que la tarjeta «Adelantos por Cancelaciones» cargara información real. Fue '
    'corregido, desplegado a producción y verificado durante esta misma auditoría (commit '
    '<b>587cb9c</b>), de modo que el panel ahora muestra los seis registros existentes.', body))

# ════ 2. INGRESOS TOTALES ════
story += heading(2, 'Ingresos Totales')
story.append(Paragraph(
    'El panel calcula los Ingresos Totales sumando dos componentes: el dinero efectivamente cobrado '
    'de las reservas <b>completadas</b> (campo <i>advance_amount</i>, que acumula adelanto más saldos '
    'abonados) y los <b>adelantos activos</b> de las reservas en estado «reservada». Quedan '
    'deliberadamente fuera del cálculo las reservas canceladas, las que esperan validación de pago '
    '(<i>payment_pending</i>) y las que aún no depositan (<i>awaiting_payment</i>); al momento de la '
    'auditoría no existían reservas en esos dos últimos estados. La composición resultante es la '
    'siguiente:', body))
story.append(Spacer(1, 8))
t2 = std_table(
    ['Componente', 'Reservas', 'Monto', 'Participación'],
    [
        ['Servicios completados (cobrado)', '65', money(3548.50), '68,2%'],
        ['Adelantos activos (reservadas)', '63', money(1655.00), '31,8%'],
        ['<b>Ingresos Totales</b>', '<b>128</b>', f'<b>{money(5203.50)}</b>', '<b>100,0%</b>'],
    ],
    [0.40, 0.14, 0.24, 0.22], [td_l, td_c, td_r, td_r], highlight_rows=[3])
story.append(KeepTogether([t2, Paragraph('Tabla 1: Composición de los Ingresos Totales según el criterio del panel de Finanzas.', caption)]))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Detectamos que la aplicación maneja <b>dos criterios simultáneos de "ingresos"</b>. El panel de '
    'Finanzas usa el criterio de caja descrito arriba (S/ 5.203,50), mientras que la tarjeta de '
    'estadísticas del endpoint /api/stats reporta S/ 5.775,50 porque contabiliza el precio total de '
    'las reservas completadas, incluidos los saldos aún no cobrados. La diferencia de S/ 572,00 '
    'corresponde exactamente a los saldos pendientes de cobro en 15 reservas ya completadas. Esta '
    'duplicidad no es un error de cálculo, pero sí una fuente de confusión operativa: se recomienda '
    'unificar el criterio o etiquetar explícitamente cada cifra en la interfaz.', body))

# ════ 3. DESGLOSE POR MÉTODO DE PAGO ════
story += heading(3, 'Desglose por Método de Pago (Yape, Plin y Efectivo)')
story.append(Paragraph(
    'Para clasificar cada sol ingresado se utilizó el método de pago registrado en la reserva: el '
    'campo <i>payment_method</i> para pagos de método único y el campo <i>payment_breakdown</i> para '
    'las reservas con pago dividido (MIXTO). No se encontraron reservas MIXTO sin desglose, por lo que '
    'el 100% del ingreso quedó clasificado. Conviene una advertencia metodológica: el método guardado '
    'corresponde al pago del adelanto que confirmó la reserva, y la colección de pagos individuales '
    'solo respalda S/ 660,00 del total (141 reservas no tienen registro de pago asociado), de modo que '
    'el desglose refleja la contabilidad de reservas, no un libro de transacciones completo.', body))
story.append(Spacer(1, 10))
img = fit_image('/home/z/my-project/scripts/audit_donut_metodo.png', AVAIL_W, PAGE_H * 0.30)
story.append(KeepTogether([img, Paragraph('Figura 1: Distribución de los Ingresos Totales por método de pago registrado (S/ 5.203,50).', caption)]))
story.append(Spacer(1, 8))
t3 = std_table(
    ['Método', 'Monto', 'Participación'],
    [
        ['Efectivo', money(3886.00), '74,7%'],
        ['Yape', money(817.50), '15,7%'],
        ['Culqi (pasarela digital)', money(435.00), '8,4%'],
        ['Plin', money(65.00), '1,2%'],
        ['<b>Subtotal Yape + Plin</b>', f'<b>{money(882.50)}</b>', '<b>17,0%</b>'],
        ['<b>Total</b>', f'<b>{money(5203.50)}</b>', '<b>100,0%</b>'],
    ],
    [0.44, 0.28, 0.28], [td_l, td_r, td_r], highlight_rows=[4])
story.append(KeepTogether([t3, Paragraph('Tabla 2: Ingresos por método de pago. El subtotal Yape + Plin responde a la consulta de esta auditoría.', caption)]))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Los cobros digitales totales (Yape, Plin y Culqi) ascienden a <b>S/ 1.317,50</b>, es decir el '
    '<b>25,3%</b> de los ingresos, mientras que el efectivo domina la recaudación con tres cuartas '
    'partes del total. Esta concentración en efectivo implica que la conciliación física de caja es el '
    'control financiero más importante del negocio, y refuerza la recomendación de registrar el '
    'desglose de método en cada pago de saldo, no solo en el adelanto inicial.', body))

# ════ 4. ADELANTOS POR CANCELACIONES ════
story += heading(4, 'Adelantos por Cancelaciones: Retenidos y Devueltos')
story.append(Paragraph(
    'Cuando se cancela una reserva que tenía adelanto, ese dinero sale del cálculo de ingresos y se '
    'reclasifica: permanece en caja si el administrador lo <b>retiene</b>, o sale de caja si se lo '
    '<b>devuelve</b> al cliente. Actualmente existen <b>20 cancelaciones con adelanto</b>: solo '
    '<b>3</b> cuentan con registro formal en la colección de adelantos y <b>17</b> carecen de '
    'clasificación. La colección contiene seis registros en total, todos en efectivo, y sus montos '
    'concilian con la tarjeta del panel (S/ 82,50 retenidos y S/ 162,00 devueltos).', body))
story.append(Spacer(1, 6))
story.append(callout_row([
    (money(82.50), 'RETENIDOS EN CAJA<br/>4 registros'),
    (money(162.00), 'DEVUELTOS AL CLIENTE<br/>2 registros'),
    ('-S/ 79,50', 'NETO RETENIDO<br/>(retenidos − devueltos)'),
]))
story.append(Spacer(1, 12))
t4 = std_table(
    ['Estado', 'Monto', 'Método', 'Fecha reserva', 'Cliente'],
    [
        ['Retenido', money(10.00), 'Efectivo', '10-jul-2026', 'Test Verify'],
        ['Retenido', money(25.00), 'Efectivo', '10-jul-2026', 'Maria Garcia'],
        ['Devuelto', money(110.00), 'Efectivo', '17-jun-2026', 'Ramón Rodríguez'],
        ['Retenido', money(25.00), 'Efectivo', '17-jun-2026', 'Test Verify'],
        ['Devuelto', money(52.00), 'Efectivo', '17-jun-2026', 'iraida'],
        ['Retenido', money(22.50), 'Efectivo', '17-jun-2026', 'carlos'],
    ],
    [0.16, 0.16, 0.16, 0.22, 0.30], [td_c, td_r, td_c, td_c, td_l])
story.append(KeepTogether([t4, Paragraph('Tabla 3: Detalle de los 6 registros de Adelantos por Cancelaciones (colección retained_advances).', caption)]))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Dos problemas de integridad afectan a esta partida. Primero, <b>3 de los 6 registros apuntan a '
    'reservas que ya no existen</b> (probablemente eliminadas sin limpiar el registro asociado): '
    'condicionan S/ 47,50 de los retenidos y S/ 52,00 de los devueltos, por lo que el saldo real de '
    'caja atribuible a cancelaciones solo puede confirmarse en S/ 35,00 netos de registros verificables. '
    'Segundo, las <b>17 cancelaciones sin clasificar</b> acumulan <b>S/ 453,50</b> cuyo destino se '
    'desconoce (¿quedó en caja o se devolvió?). Entre ellas hay al menos S/ 121,00 de reservas de '
    'aparente prueba (Test Verify, Karen, caja Areqiopa); las restantes corresponden a clientes reales '
    'como Weilhelmn (S/ 85,00), viannee (S/ 60,00), Angela Allende (S/ 32,50), Pol Antony (S/ 30,00), '
    'jhoel (S/ 25,00), Ronald Peralta (S/ 20,00), Gaby (S/ 20,00), Elmer Taco (S/ 20,00), Nestor Ramos '
    '(S/ 10,00) y un registro sin usuario asignado (S/ 30,00).', body))

# ════ 5. BALANCE ════
story += heading(5, 'Balance: Dinero en Caja')
story.append(Paragraph(
    'El balance del panel representa el dinero que debería haber físicamente en caja: a los ingresos '
    'por servicios se suman los adelantos retenidos (dinero que entró y se quedó por cancelaciones), '
    'se restan los montos devueltos a clientes y se restan los egresos registrados. Existe un único '
    'egreso de S/ 300,00 registrado el 26 de mayo de 2026, categorizado como mantenimiento. El '
    'resultado concilia exactamente con la cifra que muestra el panel de Finanzas:', body))
story.append(Spacer(1, 8))
t5 = std_table(
    ['Concepto', 'Monto'],
    [
        ['+ Ingresos por servicios', money(5203.50)],
        ['+ Adelantos retenidos en caja', money(82.50)],
        ['− Devueltos al cliente', '-' + money(162.00).replace('S/ ', 'S/ ')],
        ['− Egresos (mantenimiento, 26-may-2026)', '-' + money(300.00)],
        ['<b>Balance en caja</b>', f'<b>{money(4824.00)}</b>'],
    ],
    [0.62, 0.38], [td_l, td_r], highlight_rows=[5])
story.append(KeepTogether([t5, Paragraph('Tabla 4: Composición del Balance (Dinero en Caja) verificado contra el panel.', caption)]))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Advertimos que este balance es un balance <b>contable</b>, no un arqueo: asume que todo adelanto '
    'activo registrado fue realmente cobrado y que todo pago declarado por Yape o Plin fue validado. '
    'Los hallazgos de la sección 6 (saldo por cobrar en completadas, pagos huérfanos y adelantos sin '
    'clasificar) pueden mover la caja real en varias decenas de soles, por lo que se recomienda un '
    'arqueo físico de validación antes de tomar el balance como definitivo.', body))

# ════ 6. HALLAZGOS Y RECOMENDACIONES ════
story += heading(6, 'Hallazgos y Recomendaciones')
story.append(Paragraph(
    'Los hallazgos se ordenan por severidad. El primero fue corregido durante la propia auditoría; el '
    'resto requiere acción administrativa o de datos, y ninguno altera la aritmética del panel, que '
    'resultó correcta en todos los casos verificados.', body))
story.append(Spacer(1, 4))
hallazgos = [
    ('<b>1. Crítico — corregido.</b> El endpoint /api/retained-advances devolvía siempre 403 porque '
     'el control de acceso leía el rol sobre el objeto equivocado; la tarjeta «Adelantos por '
     'Cancelaciones» nunca cargó datos en producción. Corregido, desplegado y verificado '
     '(commit 587cb9c): la sección vuelve a ser operativa.'),
    ('<b>2. Alto — clasificar adelantos de canceladas.</b> 17 cancelaciones con adelanto (S/ 453,50) '
     'no tienen registro de retenido/devuelto, incluyendo clientes reales. Recomendación: revisar cada '
     'caso en la pestaña Finanzas, marcar su destino real y depurar los montos de prueba.'),
    ('<b>3. Medio — registros con reserva inexistente.</b> 3 registros de adelantos (S/ 99,50) apuntan '
     'a reservas eliminadas. Recomendación: confirmar si el dinero fue real; si lo fue, re-vincular o '
     'documentar; si no, eliminar el registro.'),
    ('<b>4. Medio — pagos huérfanos.</b> Existen 27 pagos sin reserva válida por S/ 590,00: 11 '
     'declarados pendientes de validar (S/ 237,50, generados por un flujo que no ancla el booking_id) '
     'y 16 marcados como cobrados (S/ 352,50) que no están en ningún ingreso. Recomendación: validar o '
     'descartar los pendientes y auditar los cobrados contra caja.'),
    ('<b>5. Medio — saldo por cobrar en completadas.</b> 15 reservas completadas conservan S/ 572,00 '
     'de saldo pendiente (una de ellas sin ningún pago). Recomendación: cobrar el saldo o marcar la '
     'bajada como pérdida antes del cierre.'),
    ('<b>6. Bajo — unificar criterios de ingresos.</b> /api/stats (S/ 5.775,50) y el panel de Finanzas '
     '(S/ 5.203,50) usan definiciones distintas de "ingreso". Recomendación: etiquetar ambas cifras o '
     'unificar el criterio para evitar decisiones sobre datos incomparables.'),
    ('<b>7. Bajo — libro de pagos incompleto.</b> La colección de pagos individuales solo respalda '
     'S/ 660,00 de los S/ 5.203,50 ingresados (141 reservas sin respaldo). Recomendación: registrar el '
     'pago de saldos con la misma disciplina que el adelanto, o asumir explícitamente advance_amount '
     'como libro mayor financiero.'),
]
for h in hallazgos:
    story.append(Paragraph(h, bullet, bulletText='•'))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'En síntesis, la contabilidad del sistema es internamente consistente y ya refleja las cifras '
    'correctas en el panel de Finanzas tras la corrección desplegada. Las prioridades inmediatas son '
    'clasificar los 17 adelantos de cancelaciones pendientes, realizar un arqueo de caja contra el '
    'balance de S/ 4.824,00 y depurar los registros huérfanos, de modo que la próxima auditoría pueda '
    'verificar el patrimonio con cero partidas en suspenso.', body))

doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
print('OK cuerpo generado')
